project_name: ipassign
builds:
   - binary: ipassign
     env:
        - CGO_ENABLED=0
     goos:
        - linux
     goarch:
        - amd64

archives:
  - id: ipassign
    format: binary
    name_template: "{{ .Binary }}.{{ .Os }}.{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
       - '^docs:'
       - '^doc:'
       - '^test:'

dockers:
   - image_templates:
      - 'cycoresystems/ipassign:{{ .Tag }}'
      - 'cycoresystems/ipassign:v{{ .Major }}'
      - 'cycoresystems/ipassign:v{{ .Major }}.{{ .Minor }}'
      - 'cycoresystems/ipassign:latest'
